### ISSUE TITLE
Declare gregorian_pt_br.js in the index.d.ts

### ISSUE THREAD

**Issue by walber-martins** [shahabyazdi/react-date-object#7]
Hello, i'm getting a error when using the pt br language, the import says that the file should be declared in the index.d.ts file

![image](https://github.com/shahabyazdi/react-date-object/assets/88101083/33cdaddc-2ff7-4a8d-878a-e0deb8c7e817)

Translation:
```
"Could not locate the declaration file for the module 'react-date-object/locales/gregorian_pt_br'. '***/frontend/node_modules/react-date-object/locales/gregorian_pt_br.js' implicitly has a 'any' type.
If the 'react-date-object' package does indeed expose this module, try adding a new declaration file (.d.ts) containing the module declare 'react-date-object/locales/gregorian_pt_br';."
```

**Comment by shahabyazdi** [comment]
Hi. Your commit is available in v2.1.8. Please let me know if it doesn't work.
